//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ttmsEntities : DbContext
    {
        public ttmsEntities()
            : base("name=ttmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<aspnetrole> aspnetroles { get; set; }
        public virtual DbSet<aspnetuserclaim> aspnetuserclaims { get; set; }
        public virtual DbSet<aspnetuserlogin> aspnetuserlogins { get; set; }
        public virtual DbSet<aspnetuser> aspnetusers { get; set; }
        public virtual DbSet<brandsmaster> brandsmasters { get; set; }
        public virtual DbSet<customeraddress> customeraddresses { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employeeattendance> employeeattendances { get; set; }
        public virtual DbSet<employeecommission> employeecommissions { get; set; }
        public virtual DbSet<employeepayment> employeepayments { get; set; }
        public virtual DbSet<employeeperformance> employeeperformances { get; set; }
        public virtual DbSet<order_employee> order_employee { get; set; }
        public virtual DbSet<order_master> order_master { get; set; }
        public virtual DbSet<order_master_items> order_master_items { get; set; }
        public virtual DbSet<orderdetail> orderdetails { get; set; }
        public virtual DbSet<orderitem> orderitems { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<productcategory> productcategories { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<productsinventory> productsinventories { get; set; }
        public virtual DbSet<purchaseentry> purchaseentries { get; set; }
        public virtual DbSet<purchaseentrypayment> purchaseentrypayments { get; set; }
        public virtual DbSet<purchaseorder> purchaseorders { get; set; }
        public virtual DbSet<saleproduct> saleproducts { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<unit> units { get; set; }
    }
}
