//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseEntryPayment
    {
        public int ID { get; set; }
        public int PurchaseEntryID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentRefNo { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PurchaseEntry PurchaseEntry { get; set; }
    }
}
